[package]
name = "manga-ocr-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
image.workspace = true

[dev-dependencies]
manga-ocr-ort = { path = "../manga-ocr-ort" }
